### ISSUE TITLE
Graffiti CSS Module - minimum file size to pass rspec

### ISSUE THREAD

**Issue by UncleDadMom** [learn-co-curriculum/phase-0-css-graffiti-lab#1]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

https://learning.flatironschool.com/courses/4706/assignments/130721?module_item_id=270435

## Describe the bug

The rspec test for this module requires cleanup.css to have a minimum of 300 bytes. I was able to complete the module with 274 bytes by compounding all the selectors so I only needed one declaration.

## What is the expected behavior?

I think minimum bytes to pass rspec should be 274

## Screenshots

![281883AD-47BC-4400-A0E3-1EFB26DE4289_1_105_c](https://user-images.githubusercontent.com/87850499/128763235-acb8b3e3-1c26-48de-a053-990d799c9891.jpeg)

## What OS are you using?

- [x] OS X
- [ ] WSL
- [ ] Linux

**Comment by lizbur10** [comment]
Hi there! Thanks for raising this issue!

While it is true that a correct solution can be coded using fewer than 300 bytes, that number was chosen because it is consistent with the way most students who are just learning are likely to write their code. The concern is that using a smaller (and more specific) number may be confusing to some students.

Good job coming up with a more efficient solution!
